### ISSUE TITLE
optimal chunks per core and rows per chunk

### ISSUE THREAD

**Issue by player1024** [ddelange/mapply#13]
#### Description

150000 rows to be processed. All columns (13) are passed to func.
The func is mapping specific column values to prespecified numbers and evals a sympy equation returning a float.
I want to use all my 16 cores (includes hyperthreading).

#### Use case / motivation / context

What is the best way of dividing the chunks? And how do I know the optimal rows per chunk and max chunks per worker in this case?

**Comment by ddelange** [comment]
Hi @player1024,

The only purpose of `chunk_size` is to avoid unnecessary multiprocessing. Most of the times (big dataframes), this value is ignored and the final chunk size is determined by `max_chunks_per_worker`.

The only reason to have `max_chunks_per_worker>1` is to account for variations in time needed per row. If each row would take exactly the same amount of time (basically never the case due to clock speed variations), you could simply set `max_chunks_per_worker=1` and trust that all of your 16 chunks (assuming 16 physical CPU cores and purely CPU bound computation) will finish at the same time. Empirically, I found a value of 8-16 suitable for most sizes of datasets. There's a trade-off when you have too many chunks, as there will be some overhead for splitting/concatenating and for transferring (pickling) data to/from the processes.

As for the task you describe: lookups (hashing) is mostly a CPU bound operation. If you're sure of the added value of additional processes on the hyperthreaded cores (e.g. the function does disk or network i/o), you can set your workers to 16. You can simply test with both 16 and -1 with a subset of data, and see if there's a significant speed up. If it's marginal or non-existent, it's most likely a CPU bound operation :) 

Hope that helps!
